Update comvert
Ability to convert single files with some formating changes

diff --git a/comvert b/comvert
--- a/comvert
+++ b/comvert
@@ -1,16 +1,16 @@
 #!/bin/bash
 
-## User Variables
-TEMP="/tmp"
+## System Variables
 INST="/opt/comvert" # Set directory to the blacklist
 
 ## Default Options
 SOURCE=$(pwd)
 INPUT="cbr"
 OUTPUT="cbz"
+TEMP="/tmp"
 
-## START
-while getopts s:i:o:q opt; do
+## User Options
+while getopts s:i:o:f: opt; do
 	case $opt in
 	s)
 		SOURCE=$OPTARG
@@ -21,53 +21,94 @@ while getopts s:i:o:q opt; do
 	o)
 		OUTPUT=$OPTARG
 		;;
+	f)
+		FILE=$OPTARG
+		;;
 	esac
 done
 
 shift $((OPTIND - 1))
 
+## Define INPUT
+if [ -z "$FILE" ]; then
+	COMIC="*.$INPUT"
+else
+	COMIC="$FILE"
+fi
+
+## Define OUTPUT
 if [ "$OUTPUT" == "cbz" ]; then
 	FORMAT="zip"
 elif [ "$OUTPUT" == "cbt" ]; then
 	FORMAT="tar"
 elif [ "$OUTPUT" == "cb7" ]; then
-	FORMAT="7z"; else
-		echo "+ Output format is not supported"
-		echo && exit 1
+	FORMAT="7z"
+else
+	{ echo "+ Output format is not supported"; echo; exit 1; }
 fi
 
 ## Output Variables
-LOG="$TEMP/comvert.log"
 LIST="$INST/blacklist.ini"
-WORK="$SOURCE/.cb_tmp"
-SUSP="$SOURCE/suspicious_files.txt"
+LOG="$TEMP/comvert.log"
+CACHE="$SOURCE/.cb_cache"
 
-[[ -f "$LOG" ]] && rm "$LOG"
-touch "$LOG" 2>/dev/null || { echo "+ Access denied to $TEMP"; exit 1; }
+## Sanity checks
+if [ ! -f "$LIST" ];then
+	{ echo "+ Could not find the Blacklist"; exit 1; }
+fi
 
-[[ -d "$WORK" ]] && rm -rf "$WORK"
-mkdir "$WORK" 2>/dev/null || { echo "+ Access denied to $SOURCE"; exit 1; }
+if [ -f "$LOG" ];then
+	rm "$LOG" \
+		|| { echo "+ Error removing old log"; exit 1; }
+	touch "$LOG" 2>/dev/null \
+		|| { echo "+ Error writing log"; exit 1; }
+else
+	touch "$LOG" 2>/dev/null \
+		|| { echo "+ Error writing log"; exit 1; }
+fi
 
-clear && exec > >(tee "$LOG")
-cd "$WORK" && echo "+ Working from $SOURCE"
+if [ -d "$CACHE" ]; then
+	rm -rf "$CACHE" \
+		|| { echo "+ Error removing old cache"; exit 1; }
+	mkdir "$CACHE" 2>/dev/null \
+		|| { echo "+ Error creating cache"; exit 1; }
+else
+	mkdir "$CACHE" 2>/dev/null \
+		|| { echo "+ Error creating cache"; exit 1; }
+fi
+
+## Start Logging
+clear
+exec > >(tee "$LOG")
+echo "+ Working from $SOURCE"
 echo
 
 ## Convert Loop
-find "$SOURCE" -name "*.$INPUT" | while read CBFILE; do
+find "$SOURCE" -name "$COMIC" | while read CBFILE; do
+
 BASENAME=`basename "$CBFILE" .$INPUT`
 DIRNAME=`dirname "$CBFILE"`
 NEWNAME="$BASENAME.$OUTPUT"
 
-echo "> Processing: $BASENAME" && mkdir "$BASENAME"
-echo "-> Extracting" && 7z x "$CBFILE" -O"$BASENAME" >/dev/null && cd "$BASENAME"
+echo "> Processing: $BASENAME"
+	cd "$CACHE"
+
+echo "-> Extracting"
+	7z x "$CBFILE" -O"$BASENAME" >/dev/null
 
 echo "--> Scanning"
 
+## Scan the Blacklist
 while read CBSCAN; do
 	CBCRED=`find -type f -iname "$CBSCAN"`
-	[[ ! -z "$CBCRED" ]] && rm "$CBCRED" && echo "--> Removed Blacklisted File"
+	if [ ! -z "$CBCRED" ]; then
+		rm "$CBCRED"
+		echo "--> Removed Blacklisted File"
+	fi
 done < "$LIST"
 
+## Scan for Suspicious files
+SUSP="$SOURCE/suspicious_files.txt"
 CBSCAN=`find -type f -iname "[x-z]*"`
 if [ ! -z "$CBSCAN" ]; then
 	echo "$BASENAME" >> "$SUSP"
@@ -76,22 +117,32 @@ if [ ! -z "$CBSCAN" ]; then
 	echo "--> Suspicious Files Logged!"
 fi
 
-echo "-> Compressing" && 7z a -t$FORMAT "$NEWNAME" * > /dev/null
-mv "$NEWNAME" "$DIRNAME"
-
-echo "> Cleaning up" && cd .. && rm -r "$BASENAME"
-echo
+echo "-> Compressing"
+	7z a -sdel -t$FORMAT "$NEWNAME" * > /dev/null
+	mv "$NEWNAME" "$DIRNAME"
 
 ## Dont delete the new file if it has the same name
-[[ "$INPUT" != "$OUTPUT" ]] &&	rm "$CBFILE"
+if [ "$INPUT" != "$OUTPUT" ]; then
+	rm "$CBFILE"
+fi
+
+echo "> Complete"
+echo
 done
 
-cd .. && rm -r "$WORK" && echo "=> Conversion Done"
+echo "=> Conversion Done"
+rmdir "$CACHE"
 echo
 
-CBDID=$(cat "$LOG" |grep -c -i "Processing") && echo "+ $CBDID archives processed"
-CBFND=$(cat "$LOG" |grep -c -i "Blacklisted") && echo "+ $CBFND files removed"
-CBMSD=$(cat "$LOG" |grep -c -i "Suspicious") && echo "+ $CBMSD suspicious archives"
+## Stats
+CBDID=$(cat "$LOG" |grep -c -i "Processing")
+CBFND=$(cat "$LOG" |grep -c -i "Blacklisted")
+CBMSD=$(cat "$LOG" |grep -c -i "Suspicious")
+
+echo "+ $CBDID archives processed"
+echo "+ $CBFND files removed"
+echo "+ $CBMSD suspicious archives"
 echo
 
+## Optionally Notify
 #notify-send Comvert "Sir, your comics are done"
